/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;


import javax.swing.JFrame;
import DBConnection.DBConnection;

/**
 *
 * @author Tech Fever
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
     
    
    public MainFrame() {
        DBConnection dbConnection = new DBConnection(); // Initialize DB connection
        
        // Frame setup
        setTitle("USINDH UNIVERSITY SYSTEM");
        setSize(800, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null); // Center the window
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        facButton = new javax.swing.JButton();
        depButton = new javax.swing.JButton();
        progButton = new javax.swing.JButton();
        batchButton = new javax.swing.JButton();
        studentButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 800));
        setMinimumSize(new java.awt.Dimension(700, 700));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("USINDH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 40, 140, 40);

        exitButton.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 0, 51));
        exitButton.setText("EXIT");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton);
        exitButton.setBounds(160, 420, 290, 49);

        facButton.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        facButton.setForeground(new java.awt.Color(255, 0, 51));
        facButton.setText("FACULTY");
        facButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facButtonActionPerformed(evt);
            }
        });
        getContentPane().add(facButton);
        facButton.setBounds(160, 120, 290, 49);

        depButton.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        depButton.setForeground(new java.awt.Color(255, 0, 51));
        depButton.setText("DEPARTMENT");
        depButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depButtonActionPerformed(evt);
            }
        });
        getContentPane().add(depButton);
        depButton.setBounds(160, 180, 290, 49);

        progButton.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        progButton.setForeground(new java.awt.Color(255, 0, 51));
        progButton.setText("PROGRAM");
        progButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                progButtonActionPerformed(evt);
            }
        });
        getContentPane().add(progButton);
        progButton.setBounds(160, 240, 290, 49);

        batchButton.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        batchButton.setForeground(new java.awt.Color(255, 0, 51));
        batchButton.setText("BATCH");
        batchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(batchButton);
        batchButton.setBounds(160, 300, 290, 49);

        studentButton.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        studentButton.setForeground(new java.awt.Color(255, 0, 51));
        studentButton.setText("STUDENT");
        studentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(studentButton);
        studentButton.setBounds(160, 360, 290, 49);

        setSize(new java.awt.Dimension(598, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void depButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depButtonActionPerformed
        // TODO add your handling code here:
        Departments dp = new Departments();
        dp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_depButtonActionPerformed

    private void progButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_progButtonActionPerformed
        // TODO add your handling code here:
        Program pg = new Program();
        pg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_progButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void studentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentButtonActionPerformed
        // TODO add your handling code here:
        Student st = new Student();
        st.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_studentButtonActionPerformed

    private void facButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facButtonActionPerformed
        // TODO add your handling code here:
        
        Faculty ob=new Faculty();
        ob.setVisible(true);
        
       this.dispose();
    }//GEN-LAST:event_facButtonActionPerformed

    private void batchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchButtonActionPerformed
        // TODO add your handling code here:
        Batch b = new Batch();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_batchButtonActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batchButton;
    private javax.swing.JButton depButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton facButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton progButton;
    private javax.swing.JButton studentButton;
    // End of variables declaration//GEN-END:variables
}
